services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j-docker
    restart: unless-stopped
    ports:
      - "7474:7474"    # Neo4j http port
      - "7473:7473"    # Bloom https port
      - "7687:7687"    # Neo4j bolt port
    environment:
      NEO4J_AUTH: "neo4j/password"
      NEO4J_PLUGINS: '["graph-data-science", "apoc", "bloom", "genai"]'
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
    volumes:
      - ./data:/data
      - ./logs:/logs
      - ./import:/import
      - ./plugins:/plugins